// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SA_TEST.Models;

namespace SA_TEST.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20181212145115_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SA_TEST.Models.TblPlateNumber", b =>
                {
                    b.Property<int>("PlateNumberID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("LGACode");

                    b.Property<string>("Owner")
                        .IsRequired();

                    b.Property<string>("platenumber")
                        .IsRequired();

                    b.Property<int>("platenumberint");

                    b.HasKey("PlateNumberID");

                    b.ToTable("PlateNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
